version: '3.8'

services:
  myjenkins-blueocean:
    image: myjenkins-blueocean:1.1
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

    environment:
      DOCKER_HOST: 'tcp://docker:2376'
      DOCKER_CERT_PATH: '/certs/client'
      DOCKER_TLS_VERIFY: '1'

    tty: true
    stdin_open: true

volumes:
  jenkins-data:
  jenkins-docker-certs:
